// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginPageTestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginPageTesting() {
    // Test name: LoginPageTesting
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5500/index.html | 
    driver.get("http://127.0.0.1:5500/index.html");
    // 2 | setWindowSize | 1058x802 | 
    driver.manage().window().setSize(new Dimension(1058, 802));
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | umera@gmail.com
    driver.findElement(By.id("email")).sendKeys("umera@gmail.com");
    // 5 | click | id=b2 | 
    driver.findElement(By.id("b2")).click();
    // 6 | click | id=b1 | 
    driver.findElement(By.id("b1")).click();
    // 7 | assertAlert | Emailid is required | 
    assertThat(driver.switchTo().alert().getText(), is("Emailid is required"));
    // 8 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 9 | type | id=email | umera@gmail.com
    driver.findElement(By.id("email")).sendKeys("umera@gmail.com");
    // 10 | click | id=b1 | 
    driver.findElement(By.id("b1")).click();
    // 11 | assertAlert | Password is required | 
    assertThat(driver.switchTo().alert().getText(), is("Password is required"));
    // 12 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 13 | type | id=password | 12345
    driver.findElement(By.id("password")).sendKeys("12345");
    // 14 | click | id=b1 | 
    driver.findElement(By.id("b1")).click();
    // 15 | assertAlert | failure try once again | 
    assertThat(driver.switchTo().alert().getText(), is("failure try once again"));
    // 16 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 17 | type | id=password | 123
    driver.findElement(By.id("password")).sendKeys("123");
    // 18 | click | id=b2 | 
    driver.findElement(By.id("b2")).click();
    // 19 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 20 | type | id=email | umera@gmail.com
    driver.findElement(By.id("email")).sendKeys("umera@gmail.com");
    // 21 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 22 | type | id=password | 123
    driver.findElement(By.id("password")).sendKeys("123");
    // 23 | click | id=b1 | 
    driver.findElement(By.id("b1")).click();
    // 24 | assertAlert | Successfully login | 
    assertThat(driver.switchTo().alert().getText(), is("Successfully login"));
    // 25 | close |  | 
    driver.close();
  }
}
